### ISSUE TITLE
Semantic UI error

### ISSUE THREAD

**Issue by andrerfneves** [richsilv/semantic-ui-modal#10]
So this is a great package. And I want to use it in my project. But I'm already using the entire semantic:ui package in my package. And your package requires semantic:ui-css. Those two overlap each other and my css gets all screwed up in my project. Any way around this?

Thanks!

**Comment by Faberle** [comment]
You just have to change:
23: -   api.use("semantic:ui-css@1.0.0 || 2.0.0", "client");
23: +  api.use("semantic:ui@1.0.0 || 2.0.0", "client");

I had the same problem and I just cloned the repo and now use it as a local package. The proper fix however would be to take either semantic:ui-css or semantic:ui depending on which one is available. Sadly I don't know how to do that using api.use.

**Comment by andrerfneves** [comment]
Awesome. Thanks @Faberle that helped a lot. Cheers
