### ISSUE TITLE
[Safari] If template contains image, then position of the modal is lower then expected.

### ISSUE THREAD

**Issue by dmitrijs-balcers** [richsilv/semantic-ui-modal#5]
Using safari I've encountered such issue, and I don't understand where is the issue.
When I was using the semantic-ui without this package, modal were represented in correct way.
Hope that you could take a look at this issue.

On chrome this is working right.

![screen shot 2015-04-03 at 17 13 36](https://cloud.githubusercontent.com/assets/2266310/6983388/e389a4da-da25-11e4-8de9-cfe7c081ffe4.png)
![screen shot 2015-04-03 at 17 15 35](https://cloud.githubusercontent.com/assets/2266310/6983391/eb68d2f2-da25-11e4-9695-d8eb7683f343.png)

Calling modal like so:
```
SemanticModal.generalModal('showCardModal', this);
```

This is template which is being used:

```
<template name="showCardModal">
    <i class="close icon"></i>

    <div class="header">
        {{title}}
    </div>
    <div class="content">
        <div class="ui medium image">
            <img src="/images/cards/elliot.jpg">
        </div>
        <div class="description">
            <!--<div class="ui header">We've auto-chosen a profile image for you.</div>-->
            <p>{{content}}</p>
        </div>
    </div>
    <div class="actions">
        <div class="ui black button">
            Nope
        </div>
        <div class="ui positive right labeled icon button">
            Yep, that's me
            <i class="checkmark icon"></i>
        </div>
    </div>
</template>
```

Maybe semantic-ui should be updated into the package?

**Comment by abernix** [comment]
@dmitrijs-balcers Have you checked this with Semantic 2.x?  Semantic just [added support for images in Modals in 2.0](http://semantic-ui.com/modules/modal.html#image-content) by using `image content` instead of `content`.

**Comment by dmitrijs-balcers** [comment]
This issue is not relevant to me anymore. But thanks for suggestion. Will close the issue now.
