### ISSUE TITLE
nooitaf:semantic-ui is deprecated

### ISSUE THREAD

**Issue by alexzaporozhets** [richsilv/semantic-ui-modal#6]
Hi, please update your package to use semantic:ui-css

https://atmospherejs.com/nooitaf/semantic-ui

**Comment by Spiralis** [comment]
I second that. The package otherwise looks like a very nice contribution :)

**Comment by richsilv** [comment]
Done, dependencies are now on `semantic:ui-css` and `semantic:ui-modal`.

Thanks for raising!
